// <auto-generated />
using System;
using Fit_Tracket_Again.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fit_Tracket_Again.Migrations
{
    [DbContext(typeof(Fit_Tracket_AgainContext))]
    partial class Fit_Tracket_AgainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fit_Tracket_Again.Models.WorkoutData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WorkoutName");

                    b.Property<int>("WorkoutReps");

                    b.Property<int>("WorkoutSets");

                    b.Property<DateTime>("WorkoutTime");

                    b.Property<int>("WorkoutWeight");

                    b.HasKey("ID");

                    b.ToTable("WorkoutData");
                });
#pragma warning restore 612, 618
        }
    }
}
